### ISSUE TITLE
debug not work for some ROS project

### ISSUE THREAD

**Issue by jacknlliu** [tonyrobotics/RoboWare#11]
If clone a ROS project [universal_robot](https://github.com/ros-industrial/universal_robot), and copy it to a `catkin_ws/src`, then get a file structure like:
```
catkin_ws
└── src
    ├── CMakeLists.txt
    └── universal_robot
```
Open this workspace with roboware, and follow the `debug` instruction, but I can't get the ros nodes and executable files in debug mode.

**Comment by tony-robotics** [comment]
`universal_robot` is a git repo name, not a ros package, your file structure should like this:
```
catkin_ws
    └── src
        ├── CMakeLists.txt
        ├── universal_robot
        ├── ur10_moveit_config
        ├── ur3_moveit_config
        ├── ur5_moveit_config
        ├── ur_bringup
        ├── ur_description
        ├── ur_driver
        ├── ur_gazebo
        ├── ur_kinematics
        └── ur_msgs
```

**Comment by jacknlliu** [comment]
Thank you very much for your reply.
