### ISSUE TITLE
Is source code available?

### ISSUE THREAD

**Issue by wolfd** [tonyrobotics/RoboWare#15]
I'm trying out this IDE, and would love to know if there's source code available.

Best,
wolfd

**Comment by wangbinhai** [comment]
Sorry but currently we haven't made it open source.

Regards
Tony

**Comment by bkinman** [comment]
When will it be open source? I was told months ago that it would be made open?

**Comment by beetleskin** [comment]
Well, although they don't upload the "source code" here, you can just grab a release and have a look into the package content. Everything lies there as plain source. The release is just a bundled version of vscode, with addons, scripts and settings. Nothing is compiled or obfuscated, as far as I remember.

**Comment by SammyRamone** [comment]
@beetleskin seems to be right
Why not make it "really" open source by putting the files directly into Github, not as .deb file? Then others could make pull request or find bugs easier.

**Comment by tony-robotics** [comment]
Roboware Studio is open sourced now! Its source code is available at https://github.com/tonyrobotics/roboware-studio.
