### ISSUE TITLE
How to find armhf package of RoboWare ?

### ISSUE THREAD

**Issue by Ahrovan** [tonyrobotics/RoboWare#20]
armhf is useful for Raspberry Pi or other linux board. How to find armhf package of RoboWare ?

**Comment by tony-robotics** [comment]
We're sorry that there is no arm version. You can develop your project by using "Remote Deploy" function in RoboWare, for more information please refer to http://www.roboware.me/#/documents -> "Tutorial" -> "Remote Deploy" section.

**Comment by juhannc** [comment]
+1 for arm64 version of RoboWare Studio ("Remote Deploy" is not always an option...)

**Comment by Ahrovan** [comment]
thanks
