### ISSUE TITLE
Debug error: "launch.json"中缺少配置"C++"

### ISSUE THREAD

**Issue by billdavidzyb** [tonyrobotics/RoboWare#27]
请问launch.json需要如何配置？安装roboware后无法调试

**Comment by tony-robotics** [comment]
请尝试以下步骤：
(1)删除当前工作区.vscode目录下的launch.json文件
(2)在RoboWare菜单栏，选择“文件-关闭工作区”
(3)重启RoboWare，打开工作区

**Comment by billdavidzyb** [comment]
谢谢，launch.json恢复了，但是出现另外一个问题
Failed to load MI Debugger: ".cpp" not in executable format: File format not recognized (from file-exec-and-symbols ".cpp"。
我的文件是ELF 64-bit LSB executable, x86-64，gdb也是x86_64-linux-gnu

**Comment by billdavidzyb** [comment]
找到错了，debug执行的是源文件，所以无法启动调试，直接对node进行debug就可以了
多谢！

**Comment by Nronaldo** [comment]
> 找到错了，debug执行的是源文件，所以无法启动调试，直接对node进行debug就可以了
> 多谢！

请问怎么对 node 进行debug呀

**Comment by billdavidzyb** [comment]
Sorry 看到比较晚了
```
cd build/devel/lib/{repository}
gdb {filename}
```
