### ISSUE TITLE
go to definition do not work in ubuntu 16.04

### ISSUE THREAD

**Issue by JWSLAM** [tonyrobotics/RoboWare#44]

**Comment by kxhit** [comment]
go to definition works well with ros.h, cv_bridge.h and so on, but doesn't work with opencv(such as opencv2/opencv.hpp opencv2/core/core.hpp cv::imread()) and pcl. Please help me!

**Comment by QiuYilin** [comment]
This is a convenient IDE except this missing of function. But if the IDE can't go to definition , it can not be named IDE.
