### ISSUE TITLE
无法列出所有引用啊？？？？

### ISSUE THREAD

**Issue by deepmeng** [tonyrobotics/RoboWare#49]
跳转到函数和变量的定义很方便啊？但是为啥没有查找所有引用（变量和函数）的功能？？？？？

**Comment by tony-robotics** [comment]
目前定义跳转功能确实存在个别无法跳转的问题（由于其所在路径未加入到搜索列表），您可上传例子或截图，我们看看具体是哪些定义。

**Comment by deepmeng** [comment]
我想用一下 vscode 原来带的 “Go to Implementation” 发现 Ctrl+F12 完全没用。
Ctrl+Shift+O 和 Ctrl+T 也没法用

**Comment by tony-robotics** [comment]
@deepmeng ，是所有的定义都无法跳转吗，还是个别的？如果是个别的，方便贴一下具体名称吗？

**Comment by deepmeng** [comment]
@tonyrobotics 跳转到定义是可以的按住ctrl+鼠标左键 或者F12，我说的是跳转到变量或函数的所有引用位置，这个没法做到，所有的都不行。

**Comment by kxhit** [comment]
@tony-robotics /opt/ros/kinetic/include/opencv-3.3.1-dev 路径下的无法跳转 我的cpp里include opencv头文件和调用opencv的函数可以编译成功 但是无法跳转 求助！！！

**Comment by deepmeng** [comment]
@kxhit 这个功能貌似确实有bug，一直没有找到有效解决方案。建议换个IDE
