### ISSUE TITLE
How to see output (ROS_INFO) when 'Runh this file'

### ISSUE THREAD

**Issue by hobbeshunter** [tonyrobotics/RoboWare#58]
When I execute a node via 'Run this file' or 'Debug this file' I don't see anything printed by ROS_INFO. Neither in 'Output' nor in 'Debug Console'. Is there a way to make those visible? Thanks in advance.

**Comment by tony-robotics** [comment]
All the logged information will be buffered and output in "Debug Console" at a time as soon as the program is terminated, which is not reasonable indeed. Thanks for your response.
